// Synthetic CASE-001 metadata (spec §5-6).
// The larger demo evidence files live in public/samples/ and are generated by
// scripts/generate-synthetic-data.mjs. All identifiers are fictional.
export const CASE_ID = "CASE-001";
export const CASE_TITLE = "Rapid Mule Account Routing";
